### ISSUE TITLE
Gap between the main view and the navigation

### ISSUE THREAD

**Issue by ErionTp** [susonthapa/curved-bottom-navigation#13]
How can I remove the gap between a view and the bottom `navigation?`

The FragmentContainerView is constrained `app:layout_constraintBottom_toTopOf="@+id/nav_view"` where the `nav_view` is the `CurvedBottomNavigationView`, in this case there is a white gap.

I cant set  `app:layout_constraintBottom_toBottomOf="parent"` cause I have some recycler view and the last item when I scroll is invisible

**Comment by susonthapa** [comment]
I don't know if I fully understand your problem, but the white gap may the result of the shadow. I think for your case it would be best to use `app:layout_constraintBottom_toBottomOf="parent"` and use give bottom padding equal to the height of the `CurvedBottomNavigationView` and then set `clipToPadding` to `false`. This way, the list items will appear behind the `BottomNavigation` and the last item will be visible as we have set the padding. Let me know if that fixes your issue. You can also attach the picture of the white gap so that I can find if there is any bugs in the library.

**Comment by ErionTp** [comment]
I did as you suggested, so I set the bottom padding of the view to 56dp, and everything is displayed correctly. Thank you

**Comment by susonthapa** [comment]
Glad to hear that, I'm closing this issue.
