### ISSUE TITLE
How to apply curved item for only the center item?

### ISSUE THREAD

**Issue by kranthisvk** [susonthapa/curved-bottom-navigation#23]

**Comment by susonthapa** [comment]
Hello, @kranthisvk I didn't get it. Can you please describe what you are trying to achieve.

**Comment by xorweak** [comment]
Hi, I am looking to achieve this too.

What I need is to keep fixed the "activeIndex" of the menu. (not really, but what is wanted is the curve to remain that "index" position) and when navigating to other menu items instead of curving the current item, mark the element with a different color or give it a sunken button effect.
